module.exports = {
  MISSING_PARAMETERS: 'MISSING_PARAMETERS',
  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
  INEXISTENT_EMAIL: 'INEXISTENT_EMAIL',
  INACCESSIBLE_DATA: 'INACCESSIBLE_DATA',
  ALREADY_VERIFIED_EMAIL: 'ALREADY_VERIFIED_EMAIL',
  INVALID_RESET_PASSWORD_TOKEN: "INVALID_RESET_PASSWORD_TOKEN"
}