module.exports = {
  JWT_OPTIONS: {
    ACCESS_TOKEN_EXPIRATION: '30 days',
    VERIFICATION_TOKEN_EXPIRATION: '1h',
    ALGORITHM: 'RS256',
  },

  TOKEN_TYPE: {
    VERIFICATION_TOKEN: 'VERIFICATION_TOKEN',
    ACCESS_TOKEN: 'ACCESS_TOKEN'
  }
}